# This script finds SNP positions of excess depth (ex. of IBD or homozygosity) 
# Outliers are defined as having a depth of more than X standard deviations (default 3) from the mean
# The required argument is: Input - a list of chromosomes (col 1) SNP positions (col 2) and the depth at that SNP (column 3)
# This file is generated by get_seg_depth.R
# The optional argument is the number of standard deviations from the mean required to be considered an outlier
# $ Rscript get_outlier_SNPs.R Germline_ibdDepth.txt

#!/usr/bin/env Rscript
args = commandArgs(trailingOnly=TRUE)
n.sds = 3

if (length(args)<1) {
  stop("One argument must be supplied", call.=FALSE)
} else if (length(args)>2) {
  stop("Too many arguments", call.=FALSE)
} else if (length(args)==2) {
  n.sds = as.numeric(args[2])
}

depth.file <- read.table(args[1], sep=" ", header=F)
upper <- mean(depth.file[,3]) + (n.sds * sd(depth.file[,3]))
outliers <- depth.file[which(depth.file[,3] >= upper),]

write.table(outliers, "", quote=F, col.names=F, row.names=F)
